Parameter mask function in services/util (#2)
clamped-params/stan pull request #5
Opened 2021-03-19 16:29 UTC by Dashadower

Issue #2

2021-03-27 17:13 UTC, bbbales2 requested changes
Comments!

2021-03-27 17:13 UTC, bbbales2 commented on test_rjson.cpp
> +#include <iostream>
This file can be deleted

2021-03-27 17:13 UTC, bbbales2 commented on src/test/unit/services/util/create_param_mask_test.cpp
> +  std::cout << stan::services::util::create_param_mask(ss, clamped) << std::endl;
I think all we need to do is add a few unit tests and we're good with this.

There's a test helper function in Math to help with these sorts of things:

So add to the top:

```cpp
#include <test/unit/math/expect_near_rel.hpp>
```

And then the syntax is:

```cpp
stan::test::expect_near_rel("clamp mask tests", A, B);
```

And then if we expect the mask to be [1, 1, 1, 0, 0, 1] just do:

```cpp
Eigen::VectorXd mask_ref(6);
mask_ref << 1, 1, 1, 0, 0, 1;
auto mask = stan::services::util::create_param_mask(ss, clamped);
stan::test::expect_near_rel("clamp mask tests", mask, mask_ref);
```

2021-03-27 17:13 UTC, bbbales2 commented on src/stan/services/util/create_param_mask.hpp
> +void recurse_obj(std::vector<double>& v, const T& rtype_obj, bool clamped){
I think the way we're working with vectors here it'll be just as efficient if we return the std::vector as a return (instead of an argument).

And so line #21 will need modified a bit.

2021-03-27 17:13 UTC, bbbales2 commented on src/test/unit/services/util/create_param_mask_test.cpp
> +  std::cout << stan::services::util::create_param_mask(ss, test_var_context) << std::endl;
The easy way to check things that aren't doubles is to use stan::test::expect_near_rel:

```cpp
// expect_near_rel comes from lib/stan_math
#include <test/unit/math/expect_near_rel.hpp>
```

So you can do something like:
```cpp
Eigen::VectorXd mask_ref(5);
mask_ref << 1, 1, 1, 0, 0;
Eigen::VectorXd mask = stan::services::util::create_param_mask(ss, test_var_context);
stan::test::expect_near_rel("mask tests", mask_ref, mask);
```

2021-03-27 17:13 UTC, bbbales2 commented on src/stan/services/util/create_param_mask.hpp
> +Eigen::VectorXd create_param_mask(std::string& unconstrained_param_str, stan::io::var_context& clamped){
Looks good. Put comments on these.

```
/**
 * Create a parameter mask from json encoded dimension information and a var_context which contains the
 * masked variables
 *
 * @param unconstrained_param_str json string
 * @param clamped var_context with clamped parameters
 * @return mask as Eigen::VectorXd with 1s for unclamped parameters and 0s for clamped parameters
 */
```

Or something like that. If it seems hard to write, just do something simpler.

2021-03-27 17:13 UTC, bbbales2 commented on src/test/unit/services/util/create_param_mask_test.cpp
> +  std::cout << stan::services::util::create_param_mask(ss, test_var_context) << std::endl;
Add a couple tests here. Like make sure scalars get masked correct, and arrays of matrices, and I guess that's good? I guess maybe a test to try to hit each edge of the recursively implemented function?

2021-03-29 13:28 UTC, Dashadower commented on test_rjson.cpp
> +#include <iostream>
Oh whoops sneaked its way into the commit lol.

2021-03-29 13:29 UTC, Dashadower commented on src/test/unit/services/util/create_param_mask_test.cpp
> +  std::cout << stan::services::util::create_param_mask(ss, clamped) << std::endl;
Added a new test; should it be sufficient or do I need to make new JSON?

2021-03-29 13:31 UTC, Dashadower commented on src/stan/services/util/create_param_mask.hpp
> +void recurse_obj(std::vector<double>& v, const T& rtype_obj, bool clamped){
I'm not sure how you mean it'll be efficient by returning a vector.

2021-03-29 13:31 UTC, Dashadower commented on src/test/unit/services/util/create_param_mask_test.cpp
> +  std::cout << stan::services::util::create_param_mask(ss, test_var_context) << std::endl;
I'll resolve this since I adress this above.

2021-03-30 23:40 UTC, bbbales2 approved these changes

2021-03-30 23:40 UTC, merged